
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;

	private global::Gtk.EventBox eventbox1;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Label label5;

	private global::Gtk.Label label4;

	private global::Gtk.Entry textBox1;

	private global::Gtk.Label label3;

	private global::Gtk.Entry textNB;

	private global::Gtk.Label label9;

	private global::Gtk.Entry textB;

	private global::Gtk.Label label8;

	private global::Gtk.Entry textA;

	private global::Gtk.Label label7;

	private global::Gtk.Label label6;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Entry textI;

	private global::Gtk.SpinButton numericUpDown1;

	private global::Gtk.Label label14;

	private global::Gtk.HScale trackBarI;

	private global::Gtk.Button button3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Viewermageddon");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 650;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 1000;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.eventbox1 = new global::Gtk.EventBox();
		this.eventbox1.WidthRequest = 700;
		this.eventbox1.HeightRequest = 700;
		this.eventbox1.Name = "eventbox1";
		this.hpaned1.Add(this.eventbox1);
		global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.eventbox1]));
		w1.Resize = false;
		w1.Shrink = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.WidthRequest = 250;
		this.fixed3.HeightRequest = 700;
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 227;
		this.button1.HeightRequest = 53;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Generate curve");
		this.fixed3.Add(this.button1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
		w2.X = 10;
		w2.Y = 350;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 227;
		this.button2.HeightRequest = 53;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Rectangle rule");
		this.fixed3.Add(this.button2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button2]));
		w3.X = 10;
		w3.Y = 450;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 227;
		this.button4.HeightRequest = 53;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Simpson\'s rule");
		this.fixed3.Add(this.button4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button4]));
		w4.X = 10;
		w4.Y = 570;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 227;
		this.button5.HeightRequest = 53;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Trapezoidal rule");
		this.fixed3.Add(this.button5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button5]));
		w5.X = 10;
		w5.Y = 510;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("number of points :");
		this.fixed3.Add(this.label5);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
		w6.X = 20;
		w6.Y = 269;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("3. Size of intervals");
		this.fixed3.Add(this.label4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
		w7.X = 10;
		w7.Y = 160;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textBox1 = new global::Gtk.Entry();
		this.textBox1.WidthRequest = 227;
		this.textBox1.HeightRequest = 31;
		this.textBox1.CanFocus = true;
		this.textBox1.Name = "textBox1";
		this.textBox1.Text = global::Mono.Unix.Catalog.GetString("x * pi + 2^4");
		this.textBox1.IsEditable = true;
		this.textBox1.InvisibleChar = '●';
		this.fixed3.Add(this.textBox1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textBox1]));
		w8.X = 19;
		w8.Y = 39;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("1. Enter an expression");
		this.fixed3.Add(this.label3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
		w9.X = 10;
		w9.Y = 20;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textNB = new global::Gtk.Entry();
		this.textNB.WidthRequest = 156;
		this.textNB.HeightRequest = 24;
		this.textNB.CanFocus = true;
		this.textNB.Name = "textNB";
		this.textNB.Text = global::Mono.Unix.Catalog.GetString("11");
		this.textNB.IsEditable = false;
		this.textNB.HasFrame = false;
		this.textNB.InvisibleChar = '●';
		this.fixed3.Add(this.textNB);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textNB]));
		w10.X = 22;
		w10.Y = 293;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.WidthRequest = 18;
		this.label9.HeightRequest = 25;
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("]");
		this.fixed3.Add(this.label9);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label9]));
		w11.X = 213;
		w11.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textB = new global::Gtk.Entry();
		this.textB.WidthRequest = 69;
		this.textB.HeightRequest = 24;
		this.textB.CanFocus = true;
		this.textB.Name = "textB";
		this.textB.Text = global::Mono.Unix.Catalog.GetString("10.5");
		this.textB.IsEditable = true;
		this.textB.HasFrame = false;
		this.textB.InvisibleChar = '●';
		this.fixed3.Add(this.textB);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textB]));
		w12.X = 145;
		w12.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.WidthRequest = 26;
		this.label8.HeightRequest = 37;
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString(",");
		this.fixed3.Add(this.label8);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
		w13.X = 122;
		w13.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textA = new global::Gtk.Entry();
		this.textA.WidthRequest = 70;
		this.textA.HeightRequest = 24;
		this.textA.CanFocus = true;
		this.textA.Name = "textA";
		this.textA.Text = global::Mono.Unix.Catalog.GetString("0.5");
		this.textA.IsEditable = true;
		this.textA.HasFrame = false;
		this.textA.InvisibleChar = '●';
		this.fixed3.Add(this.textA);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textA]));
		w14.X = 53;
		w14.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.WidthRequest = 47;
		this.label7.HeightRequest = 25;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("I = [");
		this.fixed3.Add(this.label7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
		w15.X = 14;
		w15.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("2. Choose a domain");
		this.fixed3.Add(this.label6);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
		w16.X = 10;
		w16.Y = 90;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("---------------------------------------------------------------");
		this.fixed3.Add(this.label10);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label10]));
		w17.X = 12;
		w17.Y = 70;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("---------------------------------------------------------------");
		this.fixed3.Add(this.label11);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label11]));
		w18.X = 12;
		w18.Y = 143;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("---------------------------------------------------------------");
		this.fixed3.Add(this.label12);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label12]));
		w19.X = 12;
		w19.Y = 325;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Compute area using :");
		this.fixed3.Add(this.label13);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label13]));
		w20.X = 15;
		w20.Y = 420;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textI = new global::Gtk.Entry();
		this.textI.WidthRequest = 120;
		this.textI.HeightRequest = 24;
		this.textI.CanFocus = true;
		this.textI.Name = "textI";
		this.textI.Text = global::Mono.Unix.Catalog.GetString("1.0");
		this.textI.IsEditable = true;
		this.textI.HasFrame = false;
		this.textI.InvisibleChar = '●';
		this.fixed3.Add(this.textI);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textI]));
		w21.X = 100;
		w21.Y = 220;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.numericUpDown1 = new global::Gtk.SpinButton(1D, 10D, 1D);
		this.numericUpDown1.CanFocus = true;
		this.numericUpDown1.Name = "numericUpDown1";
		this.numericUpDown1.Adjustment.PageIncrement = 1D;
		this.numericUpDown1.ClimbRate = 1D;
		this.numericUpDown1.Numeric = true;
		this.numericUpDown1.Value = 1D;
		this.fixed3.Add(this.numericUpDown1);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.numericUpDown1]));
		w22.X = 176;
		w22.Y = 650;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 94;
		this.label14.HeightRequest = 25;
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("interval :");
		this.fixed3.Add(this.label14);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label14]));
		w23.X = 15;
		w23.Y = 220;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.trackBarI = new global::Gtk.HScale(null);
		this.trackBarI.WidthRequest = 236;
		this.trackBarI.HeightRequest = 30;
		this.trackBarI.CanFocus = true;
		this.trackBarI.Name = "trackBarI";
		this.trackBarI.Adjustment.Lower = 1D;
		this.trackBarI.Adjustment.Upper = 10000D;
		this.trackBarI.Adjustment.PageIncrement = 10D;
		this.trackBarI.Adjustment.StepIncrement = 1D;
		this.trackBarI.Adjustment.Value = 1000D;
		this.trackBarI.DrawValue = false;
		this.trackBarI.Digits = 0;
		this.trackBarI.ValuePos = ((global::Gtk.PositionType)(2));
		this.fixed3.Add(this.trackBarI);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.trackBarI]));
		w24.X = 10;
		w24.Y = 181;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 158;
		this.button3.HeightRequest = 53;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Newton");
		this.fixed3.Add(this.button3);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button3]));
		w25.X = 10;
		w25.Y = 630;
		this.hpaned1.Add(this.fixed3);
		global::Gtk.Paned.PanedChild w26 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.fixed3]));
		w26.Resize = false;
		w26.Shrink = false;
		this.Add(this.hpaned1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.button1_Click);
		this.button2.Clicked += new global::System.EventHandler(this.button2_Click);
		this.button4.Clicked += new global::System.EventHandler(this.button4_Click);
		this.button5.Clicked += new global::System.EventHandler(this.button5_Click);
		this.textBox1.Changed += new global::System.EventHandler(this.textBox1_TextChanged);
		this.textB.Changed += new global::System.EventHandler(this.textB_TextChanged);
		this.textA.Changed += new global::System.EventHandler(this.textA_TextChanged);
		this.textI.Changed += new global::System.EventHandler(this.textI_TextChanged);
		this.trackBarI.ValueChanged += new global::System.EventHandler(this.trackBarI_Scroll);
		this.button3.Clicked += new global::System.EventHandler(this.button3_Click);
	}
}
